name: Deploy GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read
  pages: write # Allow deploying to GitHub Pages
  id-token: write # Allow OIDC token authentication

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use a current LTS version

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8 # Or your pnpm version
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build with SvelteKit
        # Set NODE_ENV to production to ensure correct base path is used
        run: pnpm build
        env:
          NODE_ENV: production

      - name: List files in build directory (if exists)
        run: ls -al build || echo "Build directory not found"

      - name: List files in dist directory (if exists)
        run: ls -al dist || echo "Dist directory not found"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # Change path to dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # Runs after build is complete
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
